// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace SimpleRPGGameplayTags
{
	//State_Movement 움직임 행동
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Movement_Blocked);

// 공용 State
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dashing);

	//피격상태 태그
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_Stagger);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_KnockDown);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitReact_None);

//Ability 정체성 태그
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack); //Attack Root Tag
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Sword);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_WeaponSwap);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stagger);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_KnockDown);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Death);

//Ability CoolDown 태그
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoolDown_Common_Dash);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoolDown_Sword_PowerUp);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CoolDown_Sword_ChargeAttack);

//SetByCaller
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Skill_Ratio);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_CoolDown_Duration);


//Event_Combat 공용 전투
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_HitDetect);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Damaged);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Death);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_ComboWindow_Open);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_ComboWindow_Close);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_AttackTrigger);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_Stagger);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_KnockDown);

//Event_Skill 액티브 스킬 발동
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Skill_Sword_PowerUp);


	//Monster GA Trigger Tag
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Event_Attack);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Event_Death);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Event_Stagger);

	//Monster Action Ability Define Tag
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Ability_Attack);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Ability_Attack_Melee);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Ability_Attack_Ranged);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Ability_Death);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_Ability_Stagger);

	//Monster State
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Monster_State_Stagger);

	//Player_Skill_Data
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Cost_HP);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Cost_MP);

	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Category_Active);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill_Category_Passive);

	

	//Damage_Type
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_AD_Melee);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_AD_Range);
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Type_AP);

	//Weapon_Type
	SIMPLERPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Type_Sword);
}

